### ISSUE TITLE
Workaround vs. Patcher

### ISSUE THREAD

**Issue by kermie** [OXIDprojects/patcher-2016-001#1]
Line 116: "Dieses Script führt die Schritte aus um die Sicherheitslücke 2016-001 zu schließen, nur wenn beide Funktionen ausgeführt werden ist die Sicherheitslücke geschlossen!"

That's not correct: this script applies workarounds so the shop is not directly vulnerable any more but there would still be ways to do harm. The only way to close the security leak 100% is to update the shop installation.

**Comment by kingschnulli** [comment]
How about a pull request to change the wording?

**Comment by kermie** [comment]
Sure - if you're okay with it (wanted to check this before). Give me some time as I am still busy with other stuff.

**Comment by kermie** [comment]
Done!
